version: "3.6"
services:
  mysql:
    image: mysql
    hostname: app-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: app-pass
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    restart: always